### ISSUE TITLE
Todays forecast?

### ISSUE THREAD

**Issue by theskyisthelimit** [Rudd-O/homeassistant-meteoswiss#10]
Hello, I just discovered this amazing integration. Thank you!

I was wondering if there's a way to also see today's forecast. From what I can tell, the card only displays tomorrow's forecast. Am I missing something?"

![Forecast](https://user-images.githubusercontent.com/11703464/222953089-b8e87a71-22c3-4a79-be37-915021187f89.png)

**Comment by badewanne1234** [comment]
+1 for this, on the website of Meteo Swiss, the current day is also forecasted, so it should be possible I guess. Looking for this for ages :)

**Comment by Benson17** [comment]
would be nice to have this, at the moment i only see current temperature but don't see min/max for today...

**Comment by FlohEinstein** [comment]
Today's forecast like on the Meteoswiss-App is based on the data from the API here:
https://app-prod-ws.meteoswiss-app.ch/v1/plzDetail?plz=$plz
(PLZ in 6 digits, e.g. 707800 for Lenzerheide)
You get a JSON  with all the information needed
![image](https://user-images.githubusercontent.com/13822756/233572247-0d0b29a4-e30c-40d9-a741-0d16fb7773c1.png)

Currently don't have the time to write the parser myself, but I'd gladly pay the coffee for anyone who does :-)

**Comment by razowski** [comment]
Workaround to get today forecast... ;-) I've modified the code to consider the day_0 forecast...

Replace "def forecast(self)..." call in the "/config/custom_components/meteoswiss/weather.py" by this one and reboot HA :

    def forecast(self):
        currentDate = datetime.datetime.now()
        one_day = datetime.timedelta(days=1)
        fcdata_out = []
        # Skip the first element - it's the forecast for the current day
        for forecast in self._forecastData["regionForecast"][0:]:
            # calculating date of the forecast
            #currentDate = currentDate + one_day
            data_out = {}
            data_out[ATTR_FORECAST_TIME] = currentDate.strftime("%Y-%m-%d")
            data_out[ATTR_FORECAST_NATIVE_TEMP_LOW] = float(
                forecast["temperatureMin"],
            )
            data_out[ATTR_FORECAST_NATIVE_TEMP] = float(
                forecast["temperatureMax"],
            )
            data_out[ATTR_FORECAST_CONDITION] = next(
                (
                    k
                    for k, v in CONDITION_CLASSES.items()
                    if int(forecast["iconDay"]) in v
                ),
                None,
            )
            fcdata_out.append(data_out)
            currentDate = currentDate + one_day
        return fcdata_out

**Comment by Rudd-O** [comment]
I fixed this a few weeks ago.  Original author was shaving off the first day so you couldn't get today's forecast.  I fixed that.
