### ISSUE TITLE
Missing real-time data

### ISSUE THREAD

**Issue by spasche** [Rudd-O/homeassistant-meteoswiss#17]
Hi,
Since today, weather information is not available. In the logs, I can see:
```
WARNING (MainThread) [custom_components.meteo-swiss] Station PUY provided us with no real-time data
```
I tried using other stations, but they also have the issue.

Looking at the [code](https://github.com/Rudd-O/hamsclientfork/blob/7424204eb7c8667889ad7713b85d28e602fb0ab8/hamsclientfork/client.py#L25), it looks like the following URL should return conditions for each stations, but it is currently empty:
```
curl https://data.geo.admin.ch/ch.meteoschweiz.messwerte-aktuell/VQHA80.csv
Station/Location;Date;tre200s0;rre150z0;sre000z0;gre000z0;ure200s0;tde200s0;dkl010z0;fu3010z0;fu3010z1;prestas0;pp0qffs0;pp0qnhs0;ppz850s0;ppz700s0;dv1towz0;fu3towz0;fu3towz1;ta1tows0;uretows0;tdetows0
```

**Comment by mbuerki84** [comment]
Hello,
I have the same problem..

**Comment by spasche** [comment]
Right, seems to be back 👍
