### ISSUE TITLE
Add support for long-term statistics

### ISSUE THREAD

**Issue by sebcou21** [Rudd-O/homeassistant-meteoswiss#19]
Hi, 

It would be useful to have support for long-term statistics by adding `state_class: measurement` to the sensors that support it as explained in https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics. It would allow to display min/max/mean values in the Statistics card for example.

Thanks in advance.

**Comment by Rudd-O** [comment]
I have added this in https://github.com/Rudd-O/homeassistant-meteoswiss/commits/master .

Please let me know if it works for you.
