### ISSUE TITLE
Platform not found (No module named 'custom_components.meteoswiss') error after last update

### ISSUE THREAD

**Issue by sebcou21** [Rudd-O/homeassistant-meteoswiss#20]
Hi,

Updated the integration this morning to latest and I get the following error after restart:

`2023-06-07 20:14:17.426 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform meteo-swiss.weather: Platform not found (No module named 'custom_components.meteoswiss').`

As a result the Weather Forecast Card shows that the entity is not available. However the sensors are still getting data as usual. Debug log showed no other ERROR or WARN about it. Tried deleting the integration, reinstalling and reconfiguring but the issue still persists.

Thanks in advance.

**Comment by razowski** [comment]
PS: workaround : rename the folder 'meteo-swiss' to 'meteoswiss' under custom_components folder, restart HA...

**Comment by razowski** [comment]
Forecast working on my side

**Comment by elduca** [comment]
Hi, had the same issue, confirming: works again.
Thanx for the workaround!!

**Comment by PatWolf68** [comment]
Hi, After renaming the directory, it works again. Thanks for the information

**Comment by elduca** [comment]
Hi, since the last update, yesterday the error is back. I tried to rename the folder and restart HA But the error is still there. 
Any ideas?
Regards

**Comment by razowski** [comment]
Hello,
Was the same on my Side. I've uninstalled, drop the folder renammed last week and installed it again. It's now working for me.
Hope it's help

**Comment by sebcou21** [comment]
Original issue solved and new cleanup instructions provided in README are working.

**Comment by elduca** [comment]
After following the read me everthing works!
Thanx
