### ISSUE TITLE
Unable to download.

### ISSUE THREAD

**Issue by bench66517** [Rudd-O/homeassistant-meteoswiss#21]
if i want to download the integration...it turns and turns....even i let it turn over night..in the morning it was still turning....
i dont know what to do...
![image](https://github.com/Rudd-O/homeassistant-meteoswiss/assets/132230223/41b07260-7bd7-4880-9d4a-b7e9809f2eec)

**Comment by Rudd-O** [comment]
Please delete the integration, delete the folder /config/custom_components/meteo-swiss, re-add the integration and try again.  Sorry for this issue.
