### ISSUE TITLE
Unable to prepare setup for platform meteoswiss

### ISSUE THREAD

**Issue by steuerzentrale** [Rudd-O/homeassistant-meteoswiss#22]
Hi there

I just updated to the most recent version (c0155dd) of the add-on, unfortunately I got the below error. could you please have a look at it? I removed the integration and add-on in HACS, restarted the instance and re-installed both the HACS add-on and integration, always with the below result.

HA version 2023.6.2

BTW: thanks for this nice add-on, its one of my favorites for sure!

LLogger: homeassistant.setup
Source: setup.py:377
First occurred: 22:37:20 (3 occurrences)
Last logged: 22:41:19

Unable to prepare setup for platform meteoswiss.weather: Platform not found (cannot import name 'ClientResult' from 'hamsclientfork.client' (/usr/local/lib/python3.11/site-packages/hamsclientfork/client.py)).

----------------------------------

Logger: homeassistant.helpers.integration_platform
Source: loader.py:850
First occurred: 22:37:20 (7 occurrences)
Last logged: 22:37:47

Unexpected error importing meteoswiss/logbook.py
Unexpected error importing meteoswiss/system_health.py
Unexpected error importing meteoswiss/media_source.py
Unexpected error importing meteoswiss/significant_change.py
Unexpected error importing meteoswiss/hardware.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.meteo-swiss.diagnostics'

[home-assistant_meteoswiss_2023-06-22T20-53-51.967Z.log](https://github.com/Rudd-O/homeassistant-meteoswiss/files/11840404/home-assistant_meteoswiss_2023-06-22T20-53-51.967Z.log)

**Comment by vbaros** [comment]
Same error in the latest version 2023.7.1

**Comment by Rudd-O** [comment]
You may have an out of date hamsclientfork.  Try installing hamsclientfork 0.2.8 in your HA venv.
