### ISSUE TITLE
Repair alert after HA update to 2023.9

### ISSUE THREAD

**Issue by elduca** [Rudd-O/homeassistant-meteoswiss#24]
hi there,
i recieved a repair alert on my homeassistant saying the Meteoswiss integration uses outdated forecasts witch will no longer work in HA version 2024.3.0

i just want to let you know.

i love this integration, thanx for that
Best Regards Duri

**Comment by davee640** [comment]
Will there be an update?

**Comment by mikispag** [comment]
A maintainer just needs to merge #27.

**Comment by Rudd-O** [comment]
Should be fixed now.
