### ISSUE TITLE
Warning: The meteoswiss integration is using deprecated forecast. This stops working in version 2024.3.0

### ISSUE THREAD

**Issue by jiiins** [Rudd-O/homeassistant-meteoswiss#26]
Just FYI...

**Comment by davee640** [comment]
Will there be an update?

**Comment by beathoch** [comment]
Will there be an update?

**Comment by mikispag** [comment]
A maintainer just needs to merge #27.

**Comment by sereros** [comment]
@Rudd-O could you please merge https://github.com/Rudd-O/homeassistant-meteoswiss/pull/27 ?

**Comment by Rudd-O** [comment]
Thanks so much for the contribution @mikispag.  The PR needs to be rebased onto master but other than that it looks quite good and I will merge it once that's done.

**Comment by wulfstone** [comment]
Just stumbled upono the same issue. Much appreciated @mikispag ! Looking forward to the updated version.

**Comment by Rudd-O** [comment]
It's gonna git merged boys!  Drumroll...

**Comment by yvansandoz** [comment]
Sorry for asking, is it going to be merged in the "forked" version?

**Comment by Rudd-O** [comment]
It's already merged in the forked version.  The official version is broken and won't work anymore.
