### ISSUE TITLE
Bad logger message: Expected a known int for the forecast icon, not None ((32767,))

### ISSUE THREAD

**Issue by mischaelschill** [Rudd-O/homeassistant-meteoswiss#30]
The local forecast stopped working:

Logger: custom_components.meteoswiss.weather
Source: custom_components/meteoswiss/weather.py:154
Integration: Meteo Swiss (documentation, issues)
First occurred: 07:23:28 (9 occurrences)
Last logged: 08:03:28

Bad logger message: Expected a known int for the forecast icon, not None ((32767,))

**Comment by Rudd-O** [comment]
You should no longer get this issue when there are temporary networking issues on your side.
