### ISSUE TITLE
Can't add integration

### ISSUE THREAD

**Issue by sreusr** [Rudd-O/homeassistant-meteoswiss#31]
I'm getting this error when adding the integration:
```
Fehler

Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble 
```
Any idea why?

**Comment by sreusr** [comment]
had the wrong repo, sorry. all good and thanks for the great work!

**Comment by djtrao** [comment]
> had the wrong repo, sorry. all good and thanks for the great work!

Can you say more? 
Because I have this problem too. 

I am on the Integrations page, do + ADD INTEGRATION.
Then I search for Meteo Swiss integration. (no, not another one, its the correct one)

**Error**
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by sreusr** [comment]
Are you sure it's "Meteo Swiss (forked)"? That's what you want, closing this issue now.

**Comment by sreusr** [comment]
Closing this issue now because it's solved.
