### ISSUE TITLE
How can I use the forecast max temperature of the current day in a automation condition?

### ISSUE THREAD

**Issue by vowchr** [Rudd-O/homeassistant-meteoswiss#33]
Hello everyone

I'm fairly new to Home Assistant - I've already read up on a lot of things but please excuse me if I ask a stupid question.
I would like to use the max temperature of the current day (from the forecast) for a check in an automation. The automation should only be executed if the temperature rises above 26°. Another example (but same problem) would be the query for the expected amount of rain.

How can I achieve this? In the condition block of the entity, I can only access the current values and not the forecast.
![image](https://github.com/Rudd-O/homeassistant-meteoswiss/assets/39601282/8227b79b-d1d2-4fdb-88b4-58419661869c)

Thank you very much for your help!

**Comment by Rudd-O** [comment]
The readme has an example now, of how to use the trigger + the service call response of `get_forecasts` to create a sensor that will give you that information based on the forecast of your liking.

Once you have created a sensor that has that information, you can create an automation that reacts when that information changes.
