### ISSUE TITLE
Deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by tomik671108** [Rudd-O/homeassistant-meteoswiss#34]
STATE_CLASS_MEASUREMENT was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please create a bug report at https://github.com/Rudd-O/homeassistant-meteoswiss/issues

**Comment by thor1872** [comment]
Just adding the other deprecated one.

IRRADIATION_WATTS_PER_SQUARE_METER was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfIrradiance.WATTS_PER_SQUARE_METER instead.

PRESSURE_HPA was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.HPA instead.

SPEED_KILOMETERS_PER_HOUR was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.KILOMETERS_PER_HOUR instead.

TEMP_CELSIUS was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead.

TIME_MINUTES was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead

**Comment by Rudd-O** [comment]
This issue is now fixed.
