### ISSUE TITLE
ability to add precipipation station only

### ISSUE THREAD

**Issue by JorisM** [Rudd-O/homeassistant-meteoswiss#39]
thanks a lot for the updated version. 

i use it for closing my shades under certain conditions, i.e.when it rains i want them to close. 

the readme currenlty states:

> Users of older versions of this integration may experience a problem whereby the real-time weather sensors provided by the integration don't update, and errors on the log appear frequently regarding this issue. This is caused by an older version of the code letting people configure precipitation stations as if they were weather stations. This is no longer possible, but if you have this issue, you'll have to upgrade this integration, delete the configuration and re-add it — the erroneous station no longer will appear as an option.

i assume this was done so that precipitation stations which are mentioned on https://rudd-o.com/meteostations could be imported for rain data only. 

do you think there is a way to integration precipitation stations alongside meteo-stations? i wouldn't mix them if possible, but maybe another category of entities could be created for precipation stations only?

**Comment by Rudd-O** [comment]
It's done!  Please redownload the integration and restart HA.  You will have to delete your current weather config entry and re-add it.

**Comment by JorisM** [comment]
wonderful, redownloaded and configured it. thanks!

now i get this this error log:

<img width="548" alt="image" src="https://github.com/user-attachments/assets/8507f2d3-4672-4ee9-8556-25a12dc2e5a9">

when selecting this station:

https://www.meteoswiss.admin.ch/services-and-publications/applications/measurement-values-and-measuring-networks.html#param=messwerte-niederschlag-10min&lang=en&table=false&station=WIN&chart=hour

how do i see if a station is "real time"? is there any way to tell from the meteoswiss.admin.ch page?

**Comment by Rudd-O** [comment]
Sometimes you'll get that because the data file does not contain data for that station.  If it persists, it will create a repair for you.  I assume the issue fixed itself on your side?

**Comment by JorisM** [comment]
unfortunately the issue persists:

![image](https://github.com/user-attachments/assets/a65e5fa4-2ff5-477e-8e2b-3b94dba463ef)

reloading also doesn't help. I also tried to remove/re-adding the location, to no avail.

**Comment by Rudd-O** [comment]
I will definitely need debug logs.  Please open a new ticket and paste the debug logs from the integration.  Thanks.
