### ISSUE TITLE
Feat: check whether a station provides real-time data before committing to using it.

### ISSUE THREAD

**Issue by Rudd-O** [Rudd-O/homeassistant-meteoswiss#4]
Context: https://github.com/Rudd-O/homeassistant-meteoswiss/issues/3

Currently, the integration allows the user to select and use a station that does not provide real-time data, in the last step of the configuration.  This leads to the conundrum that, after setup, the real-time weather sensors appear as unavailable (because, of course, they are, because there's no data).  In 2 or 3 hours, the user will finally get an alert that the station provides no real-time data, raised as a Home Assistant repair.

This is suboptimal, of course.

Ideally, what happens is that the user is only permitted to select a station that provides real-time data (otherwise there is no point in selecting a station — the station is only ever used for real-time data).  With that in mind, the user cannot accidentally enter into a situation where their setup has unavailable entities.  As an improvement on this design, it should also be possible for the user to select no station at all, in which case the weather sensor entities are simply not created, end of story.

This implies we have to fetch the current station data and figure out if the station is providing said data.  I believe the API module should allow us to do this.

**Comment by aschbertus** [comment]
Sounds good to me!

**Comment by aschbertus** [comment]
I found something, that might be helpful to you (not sure though):

It seems that there are two classes for stations:
Weatherstations and Precipitation station

as listed in the following document:
https://data.geo.admin.ch/ch.meteoschweiz.messnetz-automatisch/ch.meteoschweiz.messnetz-automatisch_en.csv

As I checked for a more "human" friendly representation i found this website:
https://www.meteoschweiz.admin.ch/service-und-publikationen/applikationen/messwerte-und-messnetze.html#param=messnetz-automatisch&lang=de

Here you can see again the differentiation between weather stations (circles) and precipitation station (triangles)

I clicked on a few of each, and saw that weather stations typically provide RT-data while precipitation stations don't. 

Probably you knew that already, or it is not helpful, but I thought to share.

Cheers,

Aschbert

**Comment by Rudd-O** [comment]
Thanks — it's useful to know.  That said, the solution I think remains the same — only list stations with the relevant data.

**Comment by Rudd-O** [comment]
OK.

The solution has been implemented in commit 61268ef.

Will splice the "no station data thanks" ticket into a separate issue.
