### ISSUE TITLE
list of available weather conditions?

### ISSUE THREAD

**Issue by schneich** [Rudd-O/homeassistant-meteoswiss#43]
Hi,

when I use this `{{ states('weather.winterthur') }}`, I get `cloudy` as a response. I would like to build an emergency automation to open all window shutters, if weather changes to some conditions, such as stormy, windy, raining, ...

Is there a list available of all possible states of this sensor, so that I could choose some of them?

Thank you,
Chris

**Comment by dgalli1** [comment]
https://github.com/Rudd-O/homeassistant-meteoswiss/blob/adca884270b61055a0413e5bcb6a139c7539750c/custom_components/meteoswiss/const.py#L35

**Comment by schneich** [comment]
Hi @dgalli1,

thank you very much. This helps very much!

Allow me a follow-up question: some of the weather conditions in the code do not have an ID. Does this mean, they will not come up at all?
I am mostly interested in "hail" or "exceptional".

Thank you,
Chris

**Comment by Rudd-O** [comment]
That's correct, I would need to know what the integer value for that condition is, before I add it.

**Comment by Rudd-O** [comment]
https://github.com/Rudd-O/homeassistant-meteoswiss/blob/master/custom_components/meteoswiss/const.py#L60
