### ISSUE TITLE
Impossible to setup

### ISSUE THREAD

**Issue by stefanoklett** [Rudd-O/homeassistant-meteoswiss#44]
Hi,

when I install this MeteoSwiss fork version. it appears popup asking the Location.

Then I will get: Unknown error occurred !!!

Unusable
![2024-06-16 11_39_25-Impostazioni – Home Assistant](https://github.com/Rudd-O/homeassistant-meteoswiss/assets/2768025/54633387-fe8c-4e51-917b-8db7662f7bd3)

regards
Stefano

**Comment by bedeberger** [comment]
same here

**Comment by viertch** [comment]
Same here, looks like it's an issue with the request sent to openstreetmap. Getting this error in the logs.
Also setup works if I provide a valid post code and skip the lookup based on geodata.

```
> 2024-06-18 21:33:49.097 DEBUG (SyncWorker_7) [hamsclientfork.client] Got data from OpenStreetMap: <html>
> <head>
> <title>Access blocked</title>
> </head>
> <body>
> <h1>Access blocked</h1>
> 
> <p>You have been blocked because you have violated the
> <a href="https://operations.osmfoundation.org/policies/nominatim/">usage policy</a>
> of OSM's Nominatim geocoding service. Please be aware that OSM's resources are
> limited and shared between many users. The usage policy is there to ensure that
> the service remains usable for everybody.</p>
> 
> <p>Please review the terms and make sure that your
> software adheres to the terms. You should in particular verify that you have set a
> <b>custom HTTP referrer or HTTP user agent</b> that identifies your application, and
> that you are not overusing the service with massive bulk requests.</p>
> 
> <p>If you feel that this block is unjustified or remains after you have adopted
> your usage, you may contact the Nominatim system administrator at
> nominatim@openstreetmap.org to have this block lifted.</p>
> </body>
> </head>
```

**Comment by mousaka20** [comment]
Same here

@viertch How did you manage to bypass the location dialog so that you can enter the post code?

**Comment by HansjoergC** [comment]
Same here

**Comment by dgalli1** [comment]
> @viertch How did you manage to bypass the location dialog so that you can enter the post code?

Don't know how viertch did it, but you can remove the lines which request the geodata to get your postal code and address in the file /config/custom_components/meteoswiss/config_flow.py

My modified file looks like this:
https://gist.github.com/dgalli1/19e345bd728cc13316b931168972006c

**Comment by CD-Nitrox** [comment]
Same issue, overwriting the code with the one provided by @dgalli1 worked fine.
Thanks!

**Comment by HansjoergC** [comment]
Confirm the the workaround from @dgalli1 works well.
Danke Damian

**Comment by remirr** [comment]
I tried your code but I am still getting the same error

**Comment by michaelherger** [comment]
@dgalli1 did you consider submitting a pull request? This got me past the setup, too. Thanks!

**Comment by andreasbuff** [comment]
Confirm the the workaround from @dgalli1 works well.
Danke Andreas

**Comment by DreadN** [comment]
Thanks @dgalli1 it worked!

**Comment by zieb-a** [comment]
The workaround from @dgalli1 did not work. However, using @dgalli1 code, I commented out 

`       #if errors or user_input is None:
        #    return self.async_show_form(
        #        step_id="user_two", data_schema=schema, errors=errors
        #    )`

and hardcoded: 

        `self._post_code = 8400 #int(user_input[CONF_POSTCODE])
        self._forecast_name = 'WINTERTHUR' #user_input[CONF_FORECAST_NAME].strip()
        self._update_interval = DEFAULT_UPDATE_INTERVAL #int(user_input[CONF_UPDATE_INTERVAL])`
eg
    `self._post_code = 8000
        self._forecast_name = 'ZURICH' 
        self._update_interval = DEFAULT_UPDATE_INTERVAL

**Comment by Rudd-O** [comment]
PR #50 should fix this.
