### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by Urseen** [Rudd-O/homeassistant-meteoswiss#47]
Hi everyone,

I'm trying to install the integration through the integration menu in Home Assistant after I installed in in HACS, but I'm encountering an error message: "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble."

I found a suggestion on a Reddit forum to delete the SmartThings file in the .storage folder, but this file doesn't exist in that folder. What could I do, to install the integration?

**Comment by torstendunkel** [comment]
Hi, 
having the same issue. Any suggestions so far?

**Comment by JMoro-GH** [comment]
Facing the same issue as well.. From the HA Core logs I get the following:

<img width="1132" alt="Screenshot 2024-08-13 alle 17 27 03" src="https://github.com/user-attachments/assets/02cc79f2-768e-4819-850c-78fef094ea48">

**Comment by Rudd-O** [comment]
That looks like you're using the old meteo swiss integration.  Please uninstall, set up the custom repo, and use the one that says `(forked)` in the name.

**Comment by Urseen** [comment]
Thank you very much for your reply and your work @Rudd-O !! It works as intended now!
