### ISSUE TITLE
Missing weather icons

### ISSUE THREAD

**Issue by vistalba** [Rudd-O/homeassistant-meteoswiss#52]
I've updated to the latest commit with the new daily forecasts.

Now I noticed, that some icons for weather conditions are not shown anymore:

![image](https://github.com/user-attachments/assets/7fe1f302-ed8e-4bcd-b34e-9001f63f144b)

As you can see the icons for Monday, Tuesday and Thursday are missing. 
I'm not sure, if that was already the case with the previous version as it also could depend on the Icon which Meteo Schweiz is using.
I assume an issue while mapping the MeteoSchweiz conditions to the HA conditions.

**Comment by kess78** [comment]
Try with the default HA theme, you'll see that everything is OK.
I have the same problem with a custom theme.

**Comment by vistalba** [comment]
I do not use any theme in HA, just default. But since your last commit is seems to be resolved. Thx.
