### ISSUE TITLE
Feature: optional forecast weather-station

### ISSUE THREAD

**Issue by steuerzentrale** [Rudd-O/homeassistant-meteoswiss#6]
Hi there

I used the integration with a weather-station that is not providing real-time data (DIT, zip code 8953). In the latest version of the add-on you **cannot** select weather stations that are **not providing** real-time data which makes sense.

In my case it suggests the station LAE. I only want to use the forecast from Dietikon (https://www.meteoschweiz.admin.ch/lokalprognose/dietikon/8953.html#forecast-tab=detail-view), no need for the actual temperature etc. from LAE. As of now I cannot configure the forecast from DIT because it doesnt provide real-time data.

question: Is it somehow possible to only get the forecast from a weather-station which doesnt provide real-time data?

all the best

Andrew

**Comment by Rudd-O** [comment]
Fixed in https://github.com/Rudd-O/homeassistant-meteoswiss/commit/b4685f9803cf2603c10a119635d018a9c2d47a22 .

**Comment by steuerzentrale** [comment]
oh man, you are amazing! cant wait to update the integration ;)

**Comment by steuerzentrale** [comment]
can confirm that it works great, I now have Dietikon for the forecast and LAE for the real-time data

**Comment by Rudd-O** [comment]
Also, note that you can add more than one config from the integration, so if you need forecasts from other parts of Switzerland (with or without real-time data), that will also work.
