### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by schneich** [Rudd-O/homeassistant-meteoswiss#61]
Hi,
since ~12:00 today, something has changed. The integration does only provide punctually data...

![Screenshot_2024-10-22-15-45-17-70_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/d7cedfd4-7437-44e6-bcb3-e6f4a3eb60a9)

Anybody the same problem?

Chris

**Comment by crivchri** [comment]
Same issue here.

**Comment by schneich** [comment]
It seems be to okay since 17:35.

![grafik](https://github.com/user-attachments/assets/5db9d247-79dd-4188-8240-cfbc460d4765)
