### ISSUE TITLE
Setup successful but integration fails with "Failed setup, will retry: 'iconDay'"

### ISSUE THREAD

**Issue by exoticatom** [Rudd-O/homeassistant-meteoswiss#62]
Hello, I just tried to install meter Swiss integration but I get an error "Failed setup, will retry: 'iconDay'"
Installation was fresh, from 0. 

Is there anything I can do to solve this issue? 

<img width="351" alt="image" src="https://github.com/user-attachments/assets/eb2fccc8-93f2-472e-88d7-43e5045d41c3">
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/5e0c1cfa-f5c0-4fa0-810b-02a8fca9372d">
[home-assistant_meteoswiss_2024-11-03T10-17-48.847Z.log](https://github.com/user-attachments/files/17610000/home-assistant_meteoswiss_2024-11-03T10-17-48.847Z.log)

**Comment by exoticatom** [comment]
HACS: 
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/4dcc8be4-c9b7-4bf0-8d98-6b032ad0c7ce">

rebooted several times...  removed and added from HACS, with same error.

**Comment by Rudd-O** [comment]
I've added extra code to diagnose this.  Please upgrade, restart home assistant, then check your log for errors, and send an updated copy (your first log did not properly upload but it still would have been insufficient).

**Comment by exoticatom** [comment]
Thanks! I updated and rebooted as you instructed.

Oddly, it fails when I use the postal code 8106 with “Am Furtbach 7.” But for fun, I tried using Zurich's 8003 code and “Zurich” as the location, and that worked.

And here is the log and steps I did 

cheers,

[home-assistant_meteoswiss_2024-11-10T22-52-51.455Z.log.zip](https://github.com/user-attachments/files/17693347/home-assistant_meteoswiss_2024-11-10T22-52-51.455Z.log.zip)

<img width="468" alt="image" src="https://github.com/user-attachments/assets/b7ca751d-f394-491c-ba39-23b9cb03d7aa">
<img width="468" alt="image" src="https://github.com/user-attachments/assets/f6b685db-7638-4fbb-867a-5e236c0ef5c9">
<img width="457" alt="image" src="https://github.com/user-attachments/assets/53fa3715-2d19-40c7-bb03-6543f2d9fdea">
<img width="325" alt="image" src="https://github.com/user-attachments/assets/04999b39-cb76-4603-a20f-acb15ec421f9">
<img width="468" alt="image" src="https://github.com/user-attachments/assets/034c9f61-eb01-4637-bd68-9a47b6b7ce6e">

**Comment by Rudd-O** [comment]
Thank you but your new log does not show me the text `Error while converting daily forecast` or `Error while converting hourly forecast` which is what I added in the log.

Please update again (I just released another update) and send me the log.  Happy to help you with the issue, and thanks for your patience.

**Comment by Rudd-O** [comment]
Wait.  I think I can reproduce it with that postal code you sent me.  Please stand by.

**Comment by exoticatom** [comment]
8106 - Adlikon b. Regensdorf

**Comment by Rudd-O** [comment]
Boom.  Caught the issue.  It's fairly simple — MeteoSchweiz provides no forecast for that post code in the URL we're using:

```json
{'currentWeather': {'icon': None,
                    'iconV2': None,
                    'temperature': None,
                    'time': None},
 'graph': {'precipitation10m': [],
           'precipitationMax10m': [],
           'precipitationMax1h': [],
           'precipitationMean1h': [],
           'precipitationMin10m': [],
           'precipitationMin1h': [],
           'temperatureMax1h': [],
           'temperatureMean1h': [],
           'temperatureMin1h': []},
 'plz': 0,
 'regionForecast': [{'dayDate': '2024-11-11'},
                    {'dayDate': '2024-11-12'},
                    {'dayDate': '2024-11-13'},
                    {'dayDate': '2024-11-14'},
                    {'dayDate': '2024-11-15'},
                    {'dayDate': '2024-11-16'}],
 'warningsOverview': []}
```

Now we just return None to Home Assistant.

```
PYTHONPATH=~/Projects/hamsclientfork python3 -c 'import pprint ; import hamsclientfork.client as c ; x = c.meteoSwissClient("ignored", 8106, "SMA", "ABE") ; y = x.get_typed_data() ; pprint.pprint(y)'
{'condition': [{'date': 202411102340,
                'dkl010z0': 53.0,
                'dv1towz0': None,
                'fu3010z0': 2.5,
                'fu3010z1': 7.6,
                'fu3towz0': None,
                'fu3towz1': None,
                'gre000z0': 0.0,
                'pp0qffs0': 1029.6,
                'pp0qnhs0': 1028.3,
                'ppz700s0': None,
                'ppz850s0': None,
                'prestas0': 962.3,
                'rre150z0': 0.0,
                'sre000z0': 0.0,
                'station': 'SMA',
                'ta1tows0': 3.8,
                'tde200s0': 4.1,
                'tdetows0': 3.4,
                'tre200s0': 5.6,
                'ure200s0': 90.0,
                'uretows0': 97.4},
               {'date': 202411102340,
                'dkl010z0': None,
                'dv1towz0': None,
                'fu3010z0': None,
                'fu3010z1': None,
                'fu3towz0': None,
                'fu3towz1': None,
                'gre000z0': None,
                'pp0qffs0': None,
                'pp0qnhs0': None,
                'ppz700s0': None,
                'ppz850s0': None,
                'prestas0': None,
                'rre150z0': 0.0,
                'sre000z0': None,
                'station': 'ABE',
                'ta1tows0': None,
                'tde200s0': None,
                'tdetows0': None,
                'tre200s0': None,
                'ure200s0': None,
                'uretows0': None}],
 'condition_by_station': {'ABE': {'date': 202411102340,
                                  'dkl010z0': None,
                                  'dv1towz0': None,
                                  'fu3010z0': None,
                                  'fu3010z1': None,
                                  'fu3towz0': None,
                                  'fu3towz1': None,
                                  'gre000z0': None,
                                  'pp0qffs0': None,
                                  'pp0qnhs0': None,
                                  'ppz700s0': None,
                                  'ppz850s0': None,
                                  'prestas0': None,
                                  'rre150z0': 0.0,
                                  'sre000z0': None,
                                  'station': 'ABE',
                                  'ta1tows0': None,
                                  'tde200s0': None,
                                  'tdetows0': None,
                                  'tre200s0': None,
                                  'ure200s0': None,
                                  'uretows0': None},
                          'SMA': {'date': 202411102340,
                                  'dkl010z0': 53.0,
                                  'dv1towz0': None,
                                  'fu3010z0': 2.5,
                                  'fu3010z1': 7.6,
                                  'fu3towz0': None,
                                  'fu3towz1': None,
                                  'gre000z0': 0.0,
                                  'pp0qffs0': 1029.6,
                                  'pp0qnhs0': 1028.3,
                                  'ppz700s0': None,
                                  'ppz850s0': None,
                                  'prestas0': 962.3,
                                  'rre150z0': 0.0,
                                  'sre000z0': 0.0,
                                  'station': 'SMA',
                                  'ta1tows0': 3.8,
                                  'tde200s0': 4.1,
                                  'tdetows0': 3.4,
                                  'tre200s0': 5.6,
                                  'ure200s0': 90.0,
                                  'uretows0': 97.4}},
 'forecast': None,
 'name': 'ignored'}
```

**Comment by Rudd-O** [comment]
I'm closing this issue as it's not something we can fix in MeteoSchweiz, but we have added code to handle this situation and explain to the user (via a repair issue) that the station is not returning any forecasts.

**Comment by exoticatom** [comment]
thanks  for help. Appreciated. I managed to used another zip for it.
