### ISSUE TITLE
hamsclientfork problem

### ISSUE THREAD

**Issue by chruetli** [Rudd-O/homeassistant-meteoswiss#8]
Hi

The latest homeassistant update produces the following error:

```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in hamsclientfork setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          beautifulsoup4>=4.8.2geopy>=2.0.0
                        ~~~~~~~^
      [end of output]
```

The problem is a missing `,` in `setup.py` from `hamsclientfork` :

 ```
install_requires=[
        "requests>=2.22.0",
        "pandas>=0.25.3",
        "beautifulsoup4>=4.8.2" "geopy>=2.0.0",
    ],
```

**Comment by Benson17** [comment]
I can confirm this problem - any quick fix for this? I don't find setup.py, seems it's loaded when setup is running...

**Comment by dcear** [comment]
Yes me too , i dont' find setup.py...., thank for your Help

**Comment by chruetli** [comment]
`setup.py` is found in the installation package of `https://github.com/Rudd-O/hamsclientfork`. There is probably no quick fix as an error in `setup.py` avoids running the installation of this package. I think @Rudd-O has to fix the package.

**Comment by Rudd-O** [comment]
Oh wow.  Let me fix that right away.

**Comment by Rudd-O** [comment]
A fix has been published.

**Comment by Rudd-O** [comment]
Thank you for the quick bug report!

**Comment by chruetli** [comment]
👍 thank you!!

**Comment by Rudd-O** [comment]
Please do confirm that the update works!  I confirm it works here at home but I need independent confirmation.

**Comment by phil-schneider** [comment]
It's working for me, after reinstall and restart.
Thanks a lot.

**Comment by Benson17** [comment]
It's also working for me after re-download. Many thanks!

**Comment by dcear** [comment]
Thank you very much, it works fine

**Comment by Rudd-O** [comment]
Schönes Wochenende! :100:

**Comment by razowski** [comment]
Thanks for the fix 👍
