### ISSUE TITLE
Python Problem

### ISSUE THREAD

**Issue by capo42** [Rudd-O/homeassistant-meteoswiss#9]
Hey there

Iam quite sure you saw that already, but to track it here as well..

After Installing March update the Integration stoped to ork.
Here the Logfile sentance:

Logger: homeassistant.setup
Source: setup.py:205
First occurred: 13:57:25 (1 occurrences)
Last logged: 13:57:25

Setup failed for custom integration meteo-swiss: Requirements for meteo-swiss not found: ['hamsclientfork==0.2.3'].

Regards
Capo

**Comment by Rudd-O** [comment]
Please delete the `meteo-swiss` folder from under `config/custom_components`, then re-add the integration (it's now named `meteoswiss`).  A name change necessitated a change in where the integration is installed.
